name: dorothy
"on":
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Environment"
        run: |
          env
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Trunk Check"
        uses: trunk-io/trunk-action@v1.0.0
      - name: "Configure"
        run: |
          chmod +x "$DOROTHY/commands/"*
          source "$DOROTHY/sources/environment.sh"
          "$DOROTHY/commands/dorothy" dev
        env:
          DOROTHY: ${{env.GITHUB_WORKSPACE}}
          NO_TTY: yes
          VERBOSE: yes
      - name: "Test"
        run: |
          "$DOROTHY/commands/dorothy" test
        env:
          DOROTHY: ${{env.GITHUB_WORKSPACE}}
          NO_TTY: yes
          VERBOSE: yes
