name: dorothy
"on":
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Environment"
        run: |
          env
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Trunk Check"
        uses: trunk-io/trunk-action@v1.0.0
      - name: "Configure"
        run: |
          echo "TRUNK PATH:"
          ls -la ~/.cache/trunk/cli/ || :

          export DOROTHY PATH
          DOROTHY="$(pwd)"
          PATH="$DOROTHY/commands:$PATH"

          chmod +x ./commands/*
          bash -xv  ./commands/command-exists nano
          ./commands/setup-environment-commands bash
          ./commands/dorothy dev
        env:
          NO_TTY: yes
          VERBOSE: yes
      - name: "Test"
        run: |
          ./commands/dorothy test
        env:
          NO_TTY: yes
          VERBOSE: yes
