name: dorothy
"on":
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Environment"
        run: |
          env
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Trunk Check"
        uses: trunk-io/trunk-action@v1.0.0
      - name: "Configure"
        shell: bash
        run: |
          chmod +x ./commands/*
          source ./sources/environment.sh
          env
          ./commands/dorothy dev
        env:
          NO_TTY: yes
          VERBOSE: yes
      - name: "Test"
        shell: bash
        run: |
          ./commands/dorothy test
        env:
          NO_TTY: yes
          VERBOSE: yes
